# Generated by Django 3.1.4 on 2021-01-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('TNG', 'Tenge'), ('USD', 'Dollar'), ('RUB', 'Ruble')], default='TNG', max_length=3),
        ),
    ]
